# Generated by Django 4.0.4 on 2022-05-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vunerabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=10)),
                ('cvss', models.FloatField(null=True)),
                ('publication_date', models.DateField(null=True)),
            ],
        ),
    ]
