# Generated by Django 4.0.4 on 2022-05-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vunerabilities',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
    ]
